import Link from "next/link";
import { Eye, Plus, Trash2 } from "lucide-react";
import { notFound } from "next/navigation";
import { deleteCategoryAction, deleteDealerAction, deleteProductAction, deleteRoomAction, deleteShadeAction, duplicateProductAction, updateBrandAction, updateContactAction, updateThemeAction, upsertCategoryAction } from "@/app/actions";
import { FeatureToggle, NewClientForm } from "@/components/admin-db";
import { DealerEditor, ImportStudio, ProductEditor, RoomEditor, ShadeEditor, VisualizerSpaceEditor } from "@/components/admin-editors";
import { AdminCard, AdminHeader } from "@/components/admin-shell";
import { db } from "@/lib/db";

const clientMenu=[
  ["Overview",""],["Brand Identity","brand"],["Contact & Socials","contact"],["Theme & Styling","theme"],["Homepage Sections","homepage"],["Products","products"],["Product Categories","categories"],["Shades / Color Finder","shades"],["Rooms / Inspiration Gallery","rooms"],["Visualizer Spaces","visualizer-spaces"],["Dealers / Store Locator","dealers"],["Documents","documents"],["Blog / Expert Advice","blog"],["Leads","leads"],["AI Sessions","ai-sessions"],["Imports","imports"],["Settings / Feature Flags","settings"],
] as const;

export default async function Page({params}:{params:Promise<{path:string[]}>}){
  const path=(await params).path;const first=path[0];
  if(first==="clients"&&path.length===1){const clients=await db.client.findMany({include:{_count:{select:{products:true,shades:true,leads:true,dealers:true}}},orderBy:{createdAt:"desc"}});return <><AdminHeader eyebrow="Tenant management" title="Paint brand clients" copy="Every public website is generated from tenant records." action={<Link className="admin-btn" href="/admin/clients/new"><Plus size={16}/>Create client</Link>}/><div className="grid gap-5">{clients.map(c=><AdminCard key={c.id}><div className="grid gap-5 md:grid-cols-[auto_1fr_auto] md:items-center"><span className="grid size-16 place-items-center rounded-lg text-xl font-black text-white" style={{background:c.primaryColor}}>{c.logoUrl?<img src={c.logoUrl} alt="" className="size-full rounded-lg object-contain"/>:c.name[0]}</span><div><h2 className="text-xl font-black">{c.name}</h2><p className="mt-1 text-sm text-black/45">{c.slug} · {c._count.products} products · {c._count.shades} shades · {c._count.dealers} dealers · {c._count.leads} leads</p></div><div className="flex gap-2"><Link className="admin-btn-light" href={`/admin/clients/${c.id}`}>Manage</Link><Link className="admin-btn-light" href={`/site/${c.slug}`}><Eye size={15}/></Link></div></div></AdminCard>)}</div></>}
  if(first==="clients"&&path[1]==="new")return <><AdminHeader eyebrow="New tenant" title="Create a paint brand." copy="Start with identity and contact details."/><NewClientForm/></>;
  if(first==="settings")return <><AdminHeader eyebrow="Platform settings" title="Production integrations"/><div className="grid gap-5 md:grid-cols-2">{[["PostgreSQL","Connected through Prisma adapter"],["OpenAI","Used by AI wizards when OPENAI_API_KEY is present"],["Replicate","AI-assisted wall detection uses REPLICATE_API_TOKEN"],["Supabase Storage","Server uploads use service-role storage buckets"]].map(x=><AdminCard key={x[0]}><span className="text-xs font-bold uppercase tracking-widest text-[#A55337]">{x[0]}</span><h2 className="mt-4 text-xl font-black">{x[1]}</h2></AdminCard>)}</div></>;

  const clientId=path[1];if(first!=="clients"||!clientId)return notFound();
  const client=await db.client.findUnique({where:{id:clientId},include:{featureFlag:true,homepageSections:{orderBy:{order:"asc"}}}});if(!client)return notFound();
  const section=path[2]||"";const detail=path[3];const base=`/admin/clients/${clientId}`;
  const [categories,products,shades]=await Promise.all([
    db.productCategory.findMany({where:{clientId},orderBy:{order:"asc"}}),
    db.product.findMany({where:{clientId},include:{category:true,productFeatures:{orderBy:{order:"asc"}},applicationSteps:{orderBy:{order:"asc"}}},orderBy:{updatedAt:"desc"}}),
    db.shade.findMany({where:{clientId},orderBy:{code:"asc"}}),
  ]);
  const chrome=(children:React.ReactNode)=><><ClientWorkspaceNav client={client} base={base}/>{children}</>;

  if(!section)return chrome(<><AdminHeader eyebrow="Client workspace" title={client.name} copy="Manage brand identity, products, shades, rooms, stores, imports, leads, AI sessions, and feature flags." action={<Link className="admin-btn" href={`/site/${client.slug}`}><Eye size={16}/>Preview website</Link>}/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><Count title="Products" value={products.length} href={`${base}/products`}/><Count title="Shades" value={shades.length} href={`${base}/shades`}/><Count title="Dealers" value={await db.dealer.count({where:{clientId}})} href={`${base}/dealers`}/><Count title="Leads" value={await db.lead.count({where:{clientId}})} href={`${base}/leads`}/></div><div className="mt-6"><FeatureGrid clientId={clientId} flags={client.featureFlag}/></div></>);
  if(section==="brand")return chrome(<><AdminHeader eyebrow="Brand identity" title="Edit brand system" copy="These values drive public headers, cards, SEO context and tenant identity."/><BrandForm client={client}/></>);
  if(section==="contact")return chrome(<><AdminHeader eyebrow="Contact & socials" title="Edit public contact points" copy="Footer, contact routes, WhatsApp flows, and dealer fallback use this data."/><ContactForm client={client}/></>);
  if(section==="theme")return chrome(<><AdminHeader eyebrow="Theme & styling" title="Save the public theme to the database"/><ThemeForm client={client}/></>);
  if(section==="settings"||section==="features")return chrome(<><AdminHeader eyebrow="Settings" title="Feature flags"/><FeatureGrid clientId={clientId} flags={client.featureFlag}/></>);
  if(section==="homepage")return chrome(<><AdminHeader eyebrow="Homepage sections" title="Database homepage content"/><Table columns={["Order","Key","Type","Title","Enabled"]} rows={client.homepageSections.map(s=>[s.order,s.key,s.sectionType,s.title,s.isEnabled?"Yes":"No"])}/></>);

  if(section==="products"&&detail==="new")return chrome(<><AdminHeader eyebrow="Products" title="Create product"/><ProductEditor clientId={clientId} categories={categories} shades={shades}/></>);
  if(section==="products"&&detail){const p=products.find(x=>x.id===detail);if(!p)return notFound();return chrome(<><AdminHeader eyebrow="Products" title={`Edit ${p.name}`}/><ProductEditor clientId={clientId} categories={categories} shades={shades} product={p}/></>)}
  if(section==="products")return chrome(<><AdminHeader eyebrow="Products" title="Catalogue systems" action={<Link className="admin-btn" href={`${base}/products/new`}><Plus size={16}/>New product</Link>}/><Table columns={["Product","Category","Finish","Surface","Flags","Actions"]} rows={products.map(p=>[p.name,p.category.name,p.finish,p.surface,[p.isFeatured&&"Featured",p.isNew&&"New",p.isBestSeller&&"Best seller"].filter(Boolean).join(", ")||"—",<Actions key={p.id} edit={`${base}/products/${p.id}`} preview={`/site/${client.slug}/products/${p.slug}`}><form action={duplicateProductAction}><input type="hidden" name="clientId" value={clientId}/><input type="hidden" name="id" value={p.id}/><button className="text-xs font-bold">Duplicate</button></form><DeleteForm action={deleteProductAction} id={p.id} clientId={clientId}/></Actions>])}/></>);

  if(section==="categories")return chrome(<><AdminHeader eyebrow="Product categories" title="Category manager"/><CategoryForm clientId={clientId}/><div className="mt-6"><Table columns={["Order","Name","Slug","Active",""]} rows={categories.map(c=>[c.order,c.name,c.slug,c.isActive?"Yes":"No",<DeleteForm key={c.id} action={deleteCategoryAction} id={c.id} clientId={clientId}/>])}/></div></>);

  if(section==="shades"&&detail==="new")return chrome(<><AdminHeader eyebrow="Color finder" title="Create shade"/><ShadeEditor clientId={clientId} products={products} shades={shades}/></>);
  if(section==="shades"&&detail){const s=shades.find(x=>x.id===detail);if(!s)return notFound();return chrome(<><AdminHeader eyebrow="Color finder" title={`Edit ${s.name}`}/><ShadeEditor clientId={clientId} products={products} shades={shades} shade={s}/></>)}
  if(section==="shades")return chrome(<><AdminHeader eyebrow="Color finder" title="Shade library" action={<Link className="admin-btn" href={`${base}/shades/new`}><Plus size={16}/>New shade</Link>}/><Table columns={["Swatch","Shade","Code","Family","Mood","Season","Actions"]} rows={shades.map(s=>[<span key={s.id} className="block size-8 rounded-full border border-black/10" style={{background:s.hex}}/>,s.name,s.code,s.colorFamily,s.mood,s.season||"—",<Actions key={s.id} edit={`${base}/shades/${s.id}`} preview={`/site/${client.slug}/colors/${s.slug}`}><DeleteForm action={deleteShadeAction} id={s.id} clientId={clientId}/></Actions>])}/></>);

  if(section==="dealers"&&detail==="new")return chrome(<><AdminHeader eyebrow="Store locator" title="Create dealer"/><DealerEditor clientId={clientId} categories={categories}/></>);
  if(section==="dealers"&&detail){const dealer=await db.dealer.findUnique({where:{id:detail,clientId}});if(!dealer)return notFound();return chrome(<><AdminHeader eyebrow="Store locator" title={`Edit ${dealer.name}`}/><DealerEditor clientId={clientId} categories={categories} dealer={dealer}/></>)}
  if(section==="dealers"){const dealers=await db.dealer.findMany({where:{clientId},orderBy:{createdAt:"desc"}});return chrome(<><AdminHeader eyebrow="Store locator" title="Dealers" action={<Link className="admin-btn" href={`${base}/dealers/new`}><Plus size={16}/>New dealer</Link>}/><Table columns={["Dealer","City","State","Area","Zip","Coordinates","Actions"]} rows={dealers.map(d=>[d.name,d.city,d.state||"—",d.area,d.zipCode||"—",d.latitude&&d.longitude?`${d.latitude}, ${d.longitude}`:"Missing",<Actions key={d.id} edit={`${base}/dealers/${d.id}`}><DeleteForm action={deleteDealerAction} id={d.id} clientId={clientId}/></Actions>])}/></>)}

  if(section==="rooms"&&detail==="new")return chrome(<><AdminHeader eyebrow="Rooms" title="Create inspiration room"/><RoomEditor clientId={clientId} products={products} shades={shades}/></>);
  if(section==="rooms"&&detail){const room=await db.room.findUnique({where:{id:detail,clientId}});if(!room)return notFound();return chrome(<><AdminHeader eyebrow="Rooms" title={`Edit ${room.name}`}/><RoomEditor clientId={clientId} products={products} shades={shades} room={room}/></>)}
  if(section==="rooms"){const rooms=await db.room.findMany({where:{clientId},orderBy:{order:"asc"}});return chrome(<><AdminHeader eyebrow="Inspiration gallery" title="Rooms" action={<Link className="admin-btn" href={`${base}/rooms/new`}><Plus size={16}/>New room</Link>}/><Table columns={["Preview","Room","Space","Color family","Order","Actions"]} rows={rooms.map(r=>[<div key={r.id} className="h-12 w-20 rounded bg-cover bg-center" style={{backgroundImage:`url(${r.imageUrl})`}}/>,r.name,r.space||r.roomType,r.dominantColorFamily||"—",r.order,<Actions key={r.id} edit={`${base}/rooms/${r.id}`} preview={`/site/${client.slug}/rooms/${r.slug}`}><DeleteForm action={deleteRoomAction} id={r.id} clientId={clientId}/></Actions>])}/></>)}

  if(section==="visualizer-spaces"&&detail==="new")return chrome(<><AdminHeader eyebrow="Visualizer spaces" title="Create wall mask template"/><VisualizerSpaceEditor clientId={clientId} clientSlug={client.slug} shades={shades}/></>);
  if(section==="visualizer-spaces"&&detail){const space=await db.visualizerSpace.findUnique({where:{id:detail,clientId}});if(!space)return notFound();return chrome(<><AdminHeader eyebrow="Visualizer spaces" title={`Edit ${space.name}`}/><VisualizerSpaceEditor clientId={clientId} clientSlug={client.slug} shades={shades} space={space}/></>)}
  if(section==="visualizer-spaces"){const spaces=await db.visualizerSpace.findMany({where:{clientId},orderBy:{createdAt:"desc"}});return chrome(<><AdminHeader eyebrow="Visualizer spaces" title="Room templates and masks" action={<Link className="admin-btn" href={`${base}/visualizer-spaces/new`}><Plus size={16}/>New space</Link>}/><Table columns={["Preview","Space","Room","Featured","Active","Actions"]} rows={spaces.map(s=>[<div key={s.id} className="h-12 w-20 rounded bg-cover bg-center" style={{backgroundImage:`url(${s.thumbnailUrl})`}}/>,s.name,s.space||s.roomType,s.isFeatured?"Yes":"No",s.isActive?"Yes":"No",<Actions key={s.id} edit={`${base}/visualizer-spaces/${s.id}`}/>])}/></>)}

  if(section==="imports"){const jobs=await db.importJob.findMany({where:{clientId},include:{_count:{select:{rowErrors:true}}},orderBy:{createdAt:"desc"}});return chrome(<><AdminHeader eyebrow="Excel & CSV" title="Imports" copy="Products, shades, and dealers support preview, duplicate handling, row errors, and history."/><ImportStudio clientId={clientId}/><div className="mt-6"><Table columns={["Date","File","Type","Status","Imported","Failed","Errors"]} rows={jobs.map(j=>[j.createdAt.toLocaleString(),j.fileName,j.type,j.status,j.importedRows,j.failedRows,j._count.rowErrors])}/></div></>)}
  if(section==="leads"){const rows=await db.lead.findMany({where:{clientId},orderBy:{createdAt:"desc"}});return chrome(<><AdminHeader eyebrow="CRM" title="Leads"/><Table columns={["Date","Name","Phone","City","Source","Liters","Status"]} rows={rows.map(x=>[x.createdAt.toLocaleDateString(),x.name,x.phone,x.city||"—",x.source,x.estimatedLiters?`${x.estimatedLiters} L`:"—",x.status])}/></>)}
  if(section==="ai-sessions"){const rows=await db.aISession.findMany({where:{clientId},orderBy:{createdAt:"desc"}});return chrome(<><AdminHeader eyebrow="AI telemetry" title="AI sessions"/><Table columns={["Date","Type","Input","Output"]} rows={rows.map(x=>[x.createdAt.toLocaleString(),x.type,JSON.stringify(x.inputJson).slice(0,90),JSON.stringify(x.outputJson).slice(0,90)])}/></>)}
  if(section==="documents"){const rows=await db.document.findMany({where:{clientId},include:{product:true}});return chrome(<><AdminHeader eyebrow="Technical library" title="Documents"/><Table columns={["Document","Type","Product","Description"]} rows={rows.map(x=>[x.title,x.type,x.product?.name||"Brand level",x.description])}/></>)}
  if(section==="blog"){const rows=await db.blogPost.findMany({where:{clientId}});return chrome(<><AdminHeader eyebrow="Content" title="Blog / Expert Advice"/><Table columns={["Title","Category","Status","Published"]} rows={rows.map(x=>[x.title,x.category,x.isPublished?"Published":"Draft",x.publishedAt?.toLocaleDateString()||"—"])}/></>)}
  return notFound();
}

function ClientWorkspaceNav({client,base}:{client:{name:string;slug:string};base:string}){return <div className="mb-8 rounded-2xl border border-black/6 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-xs font-black uppercase tracking-widest text-[#A55337]">Client workspace</span><h2 className="text-xl font-black">{client.name}</h2></div><Link className="admin-btn-light" href={`/site/${client.slug}`}>Preview Website</Link></div><nav className="mt-4 flex gap-2 overflow-x-auto pb-1">{clientMenu.map(([label,href])=><Link className="shrink-0 rounded-full bg-black/[.04] px-4 py-2 text-xs font-bold text-black/60 hover:bg-[#183E32] hover:text-white" href={href?`${base}/${href}`:base} key={href}>{label}</Link>)}</nav></div>}
function Count({title,value,href}:{title:string;value:number;href:string}){return <Link href={href}><AdminCard><strong className="text-4xl">{value}</strong><span className="mt-2 block text-sm text-black/40">{title}</span></AdminCard></Link>}
function Table({columns,rows}:{columns:string[];rows:React.ReactNode[][]}){return <AdminCard><div className="overflow-x-auto"><table className="admin-table"><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table>{rows.length===0&&<p className="py-14 text-center text-sm text-black/35">No records yet.</p>}</div></AdminCard>}
function Actions({edit,preview,children}:{edit?:string;preview?:string;children?:React.ReactNode}){return <div className="flex items-center gap-3"><>{edit&&<Link className="text-xs font-bold text-[#183E32]" href={edit}>Edit</Link>}{preview&&<Link className="text-xs font-bold text-[#183E32]" href={preview}>Preview</Link>}{children}</></div>}
function DeleteForm({action,id,clientId}:{action:(formData:FormData)=>Promise<void>;id:string;clientId:string}){return <form action={action}><input type="hidden" name="id" value={id}/><input type="hidden" name="clientId" value={clientId}/><button className="text-red-700" title="Delete"><Trash2 size={15}/></button></form>}
function Input({name,label,defaultValue="",type="text",required=false}:{name:string;label:string;defaultValue?:unknown;type?:string;required?:boolean}){return <label className="admin-label">{label}<input className="admin-input" name={name} type={type} required={required} defaultValue={String(defaultValue??"")}/></label>}
function Textarea({name,label,defaultValue=""}:{name:string;label:string;defaultValue?:unknown}){return <label className="admin-label md:col-span-2">{label}<textarea className="admin-input min-h-28" name={name} defaultValue={String(defaultValue??"")}/></label>}
function BrandForm({client}:{client:Record<string,unknown>}){return <AdminCard><form action={updateBrandAction} className="grid gap-5 md:grid-cols-2"><input type="hidden" name="clientId" value={String(client.id)}/><Input name="name" label="Brand name" defaultValue={client.name} required/><Input name="slug" label="Slug" defaultValue={client.slug} required/><Input name="tagline" label="Tagline" defaultValue={client.tagline}/><Input name="website" label="Website" defaultValue={client.website}/><Textarea name="description" label="Description" defaultValue={client.description}/><Input name="logoUrl" label="Logo URL" defaultValue={client.logoUrl}/><Input name="logoLightUrl" label="Light logo URL" defaultValue={client.logoLightUrl}/><Input name="logoDarkUrl" label="Dark logo URL" defaultValue={client.logoDarkUrl}/><Input name="faviconUrl" label="Favicon URL" defaultValue={client.faviconUrl}/><Input name="tone" label="Tone" defaultValue={client.tone}/><Input name="themePreset" label="Theme preset" defaultValue={client.themePreset}/><div className="md:col-span-2 rounded-xl border border-black/10 p-6"><span className="text-xs font-black uppercase tracking-widest text-[#A55337]">Live brand card</span><h2 className="mt-5 font-serif text-5xl">{String(client.name)}</h2><p className="mt-2 text-sm text-black/45">{String(client.tagline)}</p></div><button className="admin-btn md:col-span-2">Save brand identity</button></form></AdminCard>}
function ContactForm({client}:{client:Record<string,unknown>}){const fields=["phone","whatsappNumber","email","address","city","state","country","zipCode","website","facebookUrl","instagramUrl","youtubeUrl","linkedinUrl","tiktokUrl"];return <AdminCard><form action={updateContactAction} className="grid gap-5 md:grid-cols-2"><input type="hidden" name="clientId" value={String(client.id)}/>{fields.map(f=><Input key={f} name={f} label={f.replace(/([A-Z])/g," $1")} defaultValue={client[f]}/>) }<button className="admin-btn md:col-span-2">Save contact and socials</button></form></AdminCard>}
function ThemeForm({client}:{client:Record<string,unknown>}){return <AdminCard><form action={updateThemeAction} className="grid gap-5 md:grid-cols-2"><input type="hidden" name="clientId" value={String(client.id)}/>{["primaryColor","secondaryColor","accentColor","backgroundColor","surfaceColor","textColor","mutedTextColor"].map(k=><Input key={k} name={k} label={k.replace("Color"," color")} type="color" defaultValue={client[k]}/>) }<Input name="headingFont" label="Heading font" defaultValue={client.headingFont}/><Input name="bodyFont" label="Body font" defaultValue={client.bodyFont}/><Input name="buttonStyle" label="Button style" defaultValue={client.buttonStyle}/><Input name="cardStyle" label="Card style" defaultValue={client.cardStyle}/><button className="admin-btn md:col-span-2">Save theme</button></form></AdminCard>}
function CategoryForm({clientId}:{clientId:string}){return <AdminCard><form action={upsertCategoryAction} className="grid gap-5 md:grid-cols-3"><input type="hidden" name="clientId" value={clientId}/><Input name="name" label="Name" required/><Input name="slug" label="Slug"/><Input name="iconKey" label="Icon key" defaultValue="PaintBucket"/><Input name="description" label="Description"/><Input name="imageUrl" label="Image URL"/><Input name="order" label="Order" type="number" defaultValue={0}/><label className="flex items-center gap-3 text-sm font-bold"><input name="isActive" type="checkbox" defaultChecked/>Active</label><button className="admin-btn md:col-span-3">Add category</button></form></AdminCard>}
function FeatureGrid({clientId,flags}:{clientId:string;flags:Record<string,unknown>|null}){return <AdminCard><h2 className="text-xl font-black">Feature flags</h2><div className="mt-5 grid gap-3 md:grid-cols-3">{flags&&Object.entries(flags).filter(([k,v])=>k.endsWith("Enabled")&&typeof v==="boolean").map(([k,v])=><FeatureToggle key={k} clientId={clientId} name={k} label={k.replace("Enabled","").replace(/([A-Z])/g," $1")} value={v as boolean}/>)}</div></AdminCard>}
