"use client";
import { useActionState, useState } from "react";
import { useDropzone } from "react-dropzone";
import Papa from "papaparse";
import * as XLSX from "xlsx";
import { Check, Download, FileSpreadsheet, Loader2, UploadCloud } from "lucide-react";
import { createClientAction, importRowsAction, updateFeatureAction } from "@/app/actions";

const input="mt-2 w-full rounded-lg border border-black/10 bg-white px-3 py-3 outline-none focus:border-[#183E32]";
export function NewClientForm(){
  const [state,action,pending]=useActionState(createClientAction,null);
  return <form action={action} className="admin-surface max-w-3xl"><div className="grid gap-5 md:grid-cols-2">{[["name","Brand name"],["slug","URL slug"],["tagline","Tagline"],["email","Email"],["phone","Phone / WhatsApp"],["city","City"],["country","Country"]].map(([name,label])=><label className="admin-label" key={name}>{label}<input required className={input} name={name} defaultValue={name==="country"?"Pakistan":""}/></label>)}</div>{state?.error&&<p className="mt-5 text-sm font-bold text-red-700">{state.error}</p>}<button disabled={pending} className="admin-btn mt-6">{pending?<Loader2 className="animate-spin" size={16}/>:<Check size={16}/>}Create client</button></form>
}
export function FeatureToggle({clientId,name,label,value}:{clientId:string;name:string;label:string;value:boolean}){
  const [on,setOn]=useState(value);return <form action={async(fd)=>{setOn(!on);await updateFeatureAction(fd)}}><input type="hidden" name="clientId" value={clientId}/><input type="hidden" name="key" value={name}/><input type="hidden" name="value" value={String(!on)}/><button className="flex w-full items-center justify-between rounded-lg border border-black/8 bg-white p-4 text-left text-sm font-bold"><span>{label}</span><span className={`relative h-6 w-11 rounded-full ${on?"bg-[#183E32]":"bg-black/15"}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition-all ${on?"left-6":"left-1"}`}/></span></button></form>
}
export function ImportStudio({clientId}:{clientId:string}){
  const [type,setType]=useState<"products"|"shades">("shades");const [rows,setRows]=useState<Record<string,unknown>[]>([]);const [fileName,setFileName]=useState("");const [result,setResult]=useState<{imported:number;failed:number}|null>(null);const [busy,setBusy]=useState(false);const [update,setUpdate]=useState(true);
  const onDrop=async(files:File[])=>{const file=files[0];if(!file)return;setFileName(file.name);setResult(null);if(file.name.endsWith(".csv"))Papa.parse<Record<string,unknown>>(file,{header:true,skipEmptyLines:true,complete:r=>setRows(r.data)});else{const data=await file.arrayBuffer();const book=XLSX.read(data);setRows(XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]]))}};
  const {getRootProps,getInputProps,isDragActive}=useDropzone({onDrop,accept:{"text/csv":[".csv"],"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":[".xlsx"]},multiple:false});
  const run=async()=>{setBusy(true);setResult(await importRowsAction({clientId,type,fileName,rows,updateDuplicates:update}));setBusy(false)};
  const template=()=>{const headers=type==="shades"?["name","code","hex","colorFamily","temperature","mood","lightness","bestRooms","collection","description","isTrending","isColorOfYear"]:["category","name","slug","subtitle","shortDescription","longDescription","finish","sheenLevel","surface","productType","interiorExterior","coverageSqftPerLiterOneCoat","recommendedCoats","packSizes","features","benefits","priceMode"];const blob=new Blob([headers.join(",")+"\n"],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${type}-template.csv`;a.click()};
  return <div className="grid gap-6 lg:grid-cols-[.65fr_1.35fr]"><aside className="admin-surface"><h2 className="text-xl font-black">Import workflow</h2><div className="mt-6 grid gap-2">{(["products","shades"] as const).map(x=><button onClick={()=>{setType(x);setRows([])}} key={x} className={`rounded-lg px-4 py-3 text-left text-sm font-bold capitalize ${type===x?"bg-[#183E32] text-white":"bg-black/4"}`}>{x}</button>)}</div><button onClick={template} className="admin-btn-light mt-5 w-full"><Download size={15}/>Download {type} template</button><div className="mt-6 border-t border-black/8 pt-5"><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={update} onChange={e=>setUpdate(e.target.checked)} className="size-4 accent-[#183E32]"/>Update duplicate slug/code</label></div></aside><section className="admin-surface"><div {...getRootProps()} className={`grid min-h-52 place-items-center rounded-xl border border-dashed p-8 text-center ${isDragActive?"border-[#183E32] bg-[#183E32]/5":"border-black/20"}`}><input {...getInputProps()}/><div><UploadCloud className="mx-auto text-[#A55337]" size={34}/><h3 className="mt-4 font-black">Drop an Excel or CSV file</h3><p className="mt-2 text-sm text-black/40">Preview and validate every row before writing to PostgreSQL.</p></div></div>{rows.length>0&&<><div className="mt-6 flex items-center justify-between"><div><span className="text-xs text-black/40">{fileName}</span><h3 className="font-black">{rows.length} rows ready for preview</h3></div><button disabled={busy} onClick={run} className="admin-btn">{busy?<Loader2 className="animate-spin" size={16}/>:<FileSpreadsheet size={16}/>}Import valid rows</button></div><div className="mt-4 max-h-96 overflow-auto"><table className="admin-table"><thead><tr>{Object.keys(rows[0]).slice(0,6).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice(0,20).map((row,i)=><tr key={i}>{Object.values(row).slice(0,6).map((v,j)=><td key={j}>{String(v??"")}</td>)}</tr>)}</tbody></table></div></>}{result&&<div className="mt-5 rounded-lg bg-[#183E32] p-4 text-sm font-bold text-white">{result.imported} imported · {result.failed} failed. Import history and row errors were saved.</div>}</section></div>
}
