"use client";
import Link from "next/link";
import { Calculator, Menu, MessageCircle, Palette, Search, Sparkles, X } from "lucide-react";
import { usePathname } from "next/navigation";
import { useState } from "react";

type Brand={name:string;slug:string;tagline:string;primaryColor:string;secondaryColor:string;accentColor:string;backgroundColor:string;surfaceColor:string;textColor:string;mutedTextColor:string;whatsappNumber:string;phone:string;email:string;city:string;country:string;featureFlag?:Record<string,unknown>|null};
export function SiteShell({children,brand}:{children:React.ReactNode;brand:Brand}){
  const [open,setOpen]=useState(false);const pathname=usePathname();const base=`/site/${brand.slug}`;
  const all=[["Products","products",true],["Colours","colors",true],["Rooms","rooms",true],["Visualizer","visualizer",brand.featureFlag?.visualizerEnabled===true],["Calculator","paint-calculator",brand.featureFlag?.calculatorEnabled===true],["Product Finder","product-finder",brand.featureFlag?.productFinderEnabled===true],["Dealers","dealers",brand.featureFlag?.dealerLocatorEnabled===true]];const links=all.filter(x=>x[2]);
  return <div style={{"--primary":brand.primaryColor,"--secondary":brand.secondaryColor,"--accent":brand.accentColor,"--background":brand.backgroundColor,"--surface":brand.surfaceColor,"--text":brand.textColor,"--muted":brand.mutedTextColor} as React.CSSProperties} className="min-h-screen bg-[var(--background)] text-[var(--text)]"><header className="sticky top-0 z-50 border-b border-black/7 bg-[var(--background)]/92 backdrop-blur-xl"><div className="mx-auto grid h-20 max-w-[1480px] grid-cols-[1fr_auto_1fr] items-center px-5 md:px-8"><BrandMark brand={brand}/><nav className="hidden items-center gap-6 xl:flex">{links.map(([label,href])=><Link key={href as string} className={`text-[11px] font-bold uppercase tracking-[.12em] transition hover:text-[var(--accent)] ${pathname.includes(href as string)?"text-[var(--accent)]":""}`} href={`${base}/${href}`}>{label as string}</Link>)}</nav><div className="flex justify-end gap-2"><button className="hidden p-2 md:block"><Search size={18}/></button><a href={`https://wa.me/${brand.whatsappNumber}`} className="public-pill hidden md:flex"><MessageCircle size={15}/>Expert help</a><button className="p-2 xl:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav className="grid border-t border-black/8 bg-[var(--surface)] p-5 xl:hidden">{links.map(([label,href])=><Link onClick={()=>setOpen(false)} className="border-b border-black/7 py-4 text-lg font-bold" key={href as string} href={`${base}/${href}`}>{label as string}</Link>)}</nav>}</header>{children}<footer className="mt-24 bg-[#11271f] text-white"><div className="mx-auto grid max-w-[1480px] gap-12 px-6 py-20 md:grid-cols-4"><div className="md:col-span-2"><BrandMark brand={brand} light/><p className="mt-7 max-w-md text-sm leading-7 text-white/55">{brand.tagline}. A complete approach to colour, preparation, and lasting finish.</p></div><div><h3 className="footer-title">Discover</h3><div className="mt-5 grid gap-3 text-sm text-white/50">{links.slice(0,5).map(([l,h])=><Link key={h as string} href={`${base}/${h}`}>{l as string}</Link>)}</div></div><div><h3 className="footer-title">Talk to us</h3><div className="mt-5 grid gap-3 text-sm text-white/50"><span>{brand.phone}</span><span>{brand.email}</span><span>{brand.city}, {brand.country}</span></div></div></div><div className="border-t border-white/10 px-5 py-5 text-center text-xs text-white/35">Digital colours are approximate. Always approve a physical sample in the intended light and finish.</div></footer><div className="fixed bottom-3 left-1/2 z-50 flex -translate-x-1/2 gap-1 rounded-full bg-[#11271f] p-1.5 text-white shadow-2xl md:hidden">{[[Palette,"colors"],[Sparkles,"product-finder"],[Calculator,"paint-calculator"],[MessageCircle,"contact"]].map(([Icon,href])=>{const C=Icon as typeof Palette;return <Link key={href as string} href={`${base}/${href}`} className="grid size-12 place-items-center rounded-full hover:bg-white/10"><C size={18}/></Link>})}</div></div>
}
export function BrandMark({brand,light=false}:{brand:Brand;light?:boolean}){return <Link href={`/site/${brand.slug}`} className="flex items-center gap-3"><span className="relative size-10 overflow-hidden rounded-full border border-current"><i className="absolute inset-x-0 bottom-0 h-1/2 bg-[var(--secondary)]"/></span><span><strong className={`block font-serif text-xl leading-none ${light?"text-white":""}`}>{brand.name.replace(" Pakistan","")}</strong><small className={`text-[8px] font-black uppercase tracking-[.22em] ${light?"text-white/45":"text-[var(--accent)]"}`}>Colour & Performance</small></span></Link>}
export function PageHero({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <section className="border-b border-black/7 bg-[var(--surface)]"><div className="mx-auto max-w-[1480px] px-5 py-20 md:px-8 md:py-28"><span className="public-eyebrow">{eyebrow}</span><h1 className="editorial-title mt-6 max-w-5xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--muted)]">{copy}</p></div></section>}
