import Link from "next/link";
import { Activity, Bot, Building2, FileText, Package, Palette, Users } from "lucide-react";
import { AdminCard, AdminHeader } from "@/components/admin-shell";
import { db } from "@/lib/db";

export default async function Page(){
  const [clients,products,shades,leads,sessions,documents,recent]=await Promise.all([db.client.count(),db.product.count(),db.shade.count(),db.lead.count(),db.aISession.count(),db.document.count(),db.lead.findMany({take:5,orderBy:{createdAt:"desc"},include:{client:true}})]);
  const metrics=[[Building2,"Clients",clients],[Package,"Products",products],[Palette,"Shades",shades],[Users,"Leads",leads],[Bot,"AI sessions",sessions],[FileText,"Documents",documents]] as const;
  return <><AdminHeader eyebrow="Agency intelligence" title="A living portfolio of paint brands." copy="Everything on this dashboard is read from PostgreSQL." action={<Link className="admin-btn" href="/admin/clients/new">Create client</Link>}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{metrics.map(([Icon,label,value])=><AdminCard key={label}><Icon size={18} className="text-[#A55337]"/><strong className="mt-7 block text-3xl">{value}</strong><span className="text-xs text-black/40">{label}</span></AdminCard>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><AdminCard><div className="flex items-center justify-between"><h2 className="text-xl font-black">Recent leads</h2><Link className="text-xs font-bold text-[#183E32]" href="/admin/clients">Open CRM →</Link></div><div className="mt-5 overflow-x-auto"><table className="admin-table"><thead><tr><th>Name</th><th>Client</th><th>Source</th><th>City</th><th>Status</th></tr></thead><tbody>{recent.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.client.name}</td><td>{x.source}</td><td>{x.city||"—"}</td><td>{x.status}</td></tr>)}</tbody></table></div></AdminCard><AdminCard><Activity className="text-[#A55337]"/><h2 className="mt-6 text-2xl font-black">Database-backed MVP</h2><p className="mt-3 text-sm leading-6 text-black/45">Tenant settings, catalogue data, leads, AI sessions, imports, and visualizer projects persist in Supabase Postgres.</p><Link href="/admin/clients" className="admin-btn-light mt-6">Manage brands</Link></AdminCard></div></>
}
